# values.yaml

mediawiki:
  enabled: true
  deploymentStrategy: RollingUpdate

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5  # Adjust maxReplicas based on your requirements
  targetCPUUtilizationPercentage: 70  # Adjust targetCPUUtilizationPercentage based on your requirements
